# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-16 00:03
from __future__ import unicode_literals

import app_blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=256, verbose_name='\u6587\u7ae0\u57df')),
                ('title', models.CharField(max_length=256, verbose_name='\u6807\u9898')),
                ('keywords', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5173\u952e\u8bcd')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0')),
                ('content', models.FileField(blank=True, help_text='\u6587\u7ae0\u5bf9\u5e94\u7684\u5b9e\u4f53\u6587\u4ef6', null=True, upload_to=app_blog.models.get_postFilePath, verbose_name='\u5185\u5bb9')),
                ('content_html', models.FileField(blank=True, help_text='\u6587\u7ae0\u5bf9\u5e94\u7684html\u6587\u4ef6', null=True, upload_to=app_blog.models.get_postFilePath, verbose_name='\u5185\u5bb9\u8f6c\u7801')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'ordering': ['-update_time'],
                'get_latest_by': 'update_time',
                'verbose_name': '\u6587\u7ae0',
            },
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('user', 'slug')]),
        ),
    ]
