# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-07 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u680f\u76ee\u540d\u79f0')),
                ('url', models.CharField(db_index=True, max_length=256, verbose_name='\u680f\u76ee\u7f51\u5740')),
                ('info', models.TextField(default='', help_text='\u680f\u76ee\u7b80\u4ecb\uff0c\u680f\u76ee\u81ea\u5b9a\u4e49\u5bfc\u822a\u7b49\u7528\u9014', verbose_name='\u680f\u76ee\u7b80\u4ecb')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u680f\u76ee',
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='\u6807\u9898')),
                ('url', models.CharField(db_index=True, max_length=256, verbose_name='\u7f51\u5740')),
                ('keywords', models.CharField(blank=True, help_text='\u4e0d\u5199\u9ed8\u8ba4\u4e3a\u6807\u9898', max_length=256, null=True, verbose_name='\u5173\u952e\u8bcd')),
                ('description', models.TextField(blank=True, help_text='\u4e0d\u5199\u9ed8\u8ba4\u4e3a\u5185\u5bb9\u524d160\u5b57', null=True, verbose_name='\u63cf\u8ff0')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-update_time'],
                'get_latest_by': 'update_time',
                'verbose_name': '\u6587\u6863',
            },
        ),
        migrations.CreateModel(
            name='TutorialInfo',
            fields=[
                ('tutorial_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_tutorial.Tutorial')),
            ],
            bases=('app_tutorial.tutorial',),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_tutorial.Column', verbose_name='\u5f52\u5c5e\u680f\u76ee'),
        ),
    ]
