# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-07 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='content',
            field=models.TextField(blank=True, default='\u6b63\u5728\u7f16\u5199\u4e2d\u2026\u2026', help_text='\u6587\u6863\u6b63\u6587\u5185\u5bb9', null=True, verbose_name='\u5185\u5bb9'),
        ),
    ]
