# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-14 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tutorial', '0002_auto_20181014_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='\u5173\u952e\u8bcd'),
        ),
    ]
