# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-07 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tutorial', '0002_tutorial_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialinfo',
            name='tutorial_ptr',
        ),
        migrations.RemoveField(
            model_name='column',
            name='url',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='url',
        ),
        migrations.AddField(
            model_name='column',
            name='slug',
            field=models.CharField(db_index=True, default='', max_length=256, verbose_name='\u680f\u76ee\u57df'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='slug',
            field=models.CharField(db_index=True, default='', max_length=256, verbose_name='\u57df'),
        ),
        migrations.DeleteModel(
            name='TutorialInfo',
        ),
    ]
