# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tutorial', '0003_auto_20181007_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='content',
            field=models.FileField(blank=True, help_text='\u6587\u6863\u5bf9\u5e94\u7684\u5b9e\u4f53\u6587\u4ef6', null=True, upload_to='app_tutorial/doc/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='keywords',
            field=models.CharField(blank=True, default='', help_text='\u4e0d\u5199\u9ed8\u8ba4\u4e3a\u6807\u9898', max_length=256, null=True, verbose_name='\u5173\u952e\u8bcd'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='slug',
            field=models.CharField(db_index=True, default='', max_length=256, verbose_name='\u6587\u6863\u57df'),
        ),
    ]
