# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tutorial', '0006_auto_20181010_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='slug',
            field=models.CharField(db_index=True, max_length=256, verbose_name='\u680f\u76ee\u57df'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='slug',
            field=models.CharField(db_index=True, max_length=256, verbose_name='\u6587\u6863\u57df'),
        ),
    ]
