# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 08:41
from __future__ import unicode_literals

import app_user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userpath', models.CharField(max_length=256, verbose_name='\u7528\u6237\u81ea\u5b9a\u4e49\u8def\u5f84')),
                ('filename', models.CharField(max_length=256, verbose_name='\u6587\u4ef6\u540d\u79f0')),
                ('file', models.FileField(upload_to=app_user.models.get_filePathAndName, verbose_name='\u6587\u4ef6\u5b9e\u4f53')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6240\u5c5e\u7528\u6237')),
            ],
            options={
                'ordering': ['-upload_time'],
                'get_latest_by': 'upload_time',
                'verbose_name': '\u6587\u4ef6',
            },
        ),
        migrations.AlterUniqueTogether(
            name='panfile',
            unique_together=set([('user', 'userpath', 'filename')]),
        ),
    ]
