# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 23:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(default='', max_length=256, verbose_name='\u6587\u4ef6\u8def\u5f84')),
                ('filename', models.CharField(default='', max_length=256, verbose_name='\u6587\u4ef6\u540d\u79f0')),
                ('file', models.FileField(blank=True, null=True, upload_to='app_user/pan/<django.db.models.fields.CharField>/<django.db.models.fields.CharField>', verbose_name='\u6587\u4ef6\u5b9e\u4f53')),
                ('username', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6240\u5c5e\u7528\u6237')),
            ],
            options={
                'ordering': ['filepath'],
                'verbose_name': '\u6587\u4ef6\u670d\u52a1',
            },
        ),
    ]
