# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panfile',
            options={'get_latest_by': 'upload_time', 'ordering': ['-upload_time'], 'verbose_name': '\u6587\u4ef6\u670d\u52a1'},
        ),
        migrations.AddField(
            model_name='panfile',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u4e0a\u4f20\u65f6\u95f4'),
            preserve_default=False,
        ),
    ]
