# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_auto_20181009_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=['app_user/pan/', models.CharField(default='', max_length=256, verbose_name='\u6587\u4ef6\u8def\u5f84'), models.CharField(default='', max_length=256, verbose_name='\u6587\u4ef6\u540d\u79f0')], verbose_name='\u6587\u4ef6\u5b9e\u4f53'),
        ),
    ]
