# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 00:34
from __future__ import unicode_literals

import app_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_auto_20181010_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=app_user.models.get_filePathAndName, verbose_name='\u6587\u4ef6\u5b9e\u4f53'),
        ),
    ]
