# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-12 18:42
from __future__ import unicode_literals

import app_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_auto_20181010_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panfile',
            name='file',
            field=models.FileField(default=1, upload_to=app_user.models.get_filePathAndName, verbose_name='\u6587\u4ef6\u5b9e\u4f53'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='panfile',
            name='filename',
            field=models.CharField(max_length=256, verbose_name='\u6587\u4ef6\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='panfile',
            name='userpath',
            field=models.CharField(max_length=256, verbose_name='\u7528\u6237\u81ea\u5b9a\u4e49\u8def\u5f84'),
        ),
    ]
