# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-14 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_auto_20181012_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panfile',
            options={'get_latest_by': 'upload_time', 'ordering': ['-upload_time'], 'verbose_name': '\u6587\u4ef6'},
        ),
    ]
